# Generated by Django 2.0.6 on 2018-07-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20180704_1451'),
    ]

    operations = [
    ]
